# Generated by Django 2.2.4 on 2021-01-11 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_companyuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(through='company.CompanyUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
