# Generated by Django 2.2.4 on 2021-01-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyuser_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(through='company.CompanyUser', to='company.Company'),
        ),
    ]
